name: Deploy

on:
  release:
    types: [published]

jobs:
  preflight:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          path: source

      - name: Version message
        run: echo Deploying version ${GITHUB_REF}

  framework:
    runs-on: ubuntu-latest

    needs: preflight

    steps:
      - name: Checkout framework
        uses: actions/checkout@v2
        with:
          repository: codeigniter4/framework
          path: framework

      - name: Deploy framework
        run: admin/release-framework ${GITHUB_WORKSPACE}/source ${GITHUB_WORKSPACE}/framework ${GITHUB_REF}
        working-directory: source

  appstarter:
    runs-on: ubuntu-latest

    needs: preflight

    steps:
      - name: Checkout appstarter
        uses: actions/checkout@v2
        with:
          repository: codeigniter4/appstarter
          path: appstarter

      - name: Deploy appstarter
        run: admin/release-appstarter ${GITHUB_WORKSPACE}/source ${GITHUB_WORKSPACE}/appstarter ${GITHUB_REF}
        working-directory: source
