name: Deploy

on:
  release:
    types: [published]

jobs:
  framework:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          path: source

      - name: Checkout framework
        uses: actions/checkout@v2
        with:
          repository: codeigniter4/framework
          path: framework

      - name: Allow execution
        run: chmod +x ./source/admin/release-framework

      - name: Deploy framework
        run: ./source/admin/release-framework ${GITHUB_WORKSPACE}/source ${GITHUB_WORKSPACE}/framework ${GITHUB_REF##*/}

  appstarter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          path: source

      - name: Checkout appstarter
        uses: actions/checkout@v2
        with:
          repository: codeigniter4/appstarter
          path: appstarter

      - name: Allow execution
        run: chmod +x ./source/admin/release-appstarter

      - name: Deploy appstarter
        run: ./source/admin/release-appstarter ${GITHUB_WORKSPACE}/source ${GITHUB_WORKSPACE}/appstarter ${GITHUB_REF##*/}
