name: Deploy

on:
  release:
    types: [published]

jobs:
  preflight:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          path: source

      - name: Determine version
        run: echo ${GITHUB_REF##*/}

      - name: Show environment
        run: echo `pwd` "`ls`"

  framework:
    runs-on: ubuntu-latest

    needs: preflight

    steps:
      - name: Checkout framework
        uses: actions/checkout@v2
        with:
          repository: codeigniter4/framework
          path: framework

      - name: Deploy framework
        run: ./source/admin/release-framework ${GITHUB_WORKSPACE}/source ${GITHUB_WORKSPACE}/framework ${GITHUB_REF##*/}

  appstarter:
    runs-on: ubuntu-latest

    needs: preflight

    steps:
      - name: Checkout appstarter
        uses: actions/checkout@v2
        with:
          repository: codeigniter4/appstarter
          path: appstarter

      - name: Deploy appstarter
        run: ${GITHUB_WORKSPACE}/source/admin/release-appstarter ${GITHUB_WORKSPACE}/source ${GITHUB_WORKSPACE}/appstarter ${GITHUB_REF##*/}
